import Navbar from "@/components/navbar";
import "../app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="../app/globals.css" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
